config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  get 'about', to:'about#index'

  get 'sign_up', to:'registration#new'
  post 'sign_up', to:'registration#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  
  delete 'logout', to:'sessions#destroy'

  root to:'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format: {with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
   
    def new
        @user = User.new
    end

    def create
       @user = User.new(user_params)
       if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Created Account Successfully"
       else
        render :new
       end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid email or password"
            redirect_to sign_in_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to sign_in_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1> about page </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%=render partial: 'shared/navbar'%>
    <div class="container">
      <%=render partial: 'shared/flash'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class= "d-flex align-items-center justify-content-center">
<h1> Welcome to the Main page </h1>
</div>
<div>
<% if @user %>
    Logged in as: <%= @user.email%>
    <%= button_to "Logout", logout_path, method: :delete %>
<% end %>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success mt-4" role="alert">
        <%=flash[:notice]%>
    </div> 
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
        <%=flash[:alert]%>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%=link_to "Navbar", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%=link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%=link_to "About", about_path, class: "nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>